/*
Copyright (C) 2016  The AlterPCB team
Contact: Maarten Baert <maarten-baert@hotmail.com>

This file is part of AlterPCB.

AlterPCB is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

AlterPCB is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this AlterPCB.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "FemMatrix.h"

#include "MiscMath.h"

// The following code was generated by the 'fem-matrix-generator.py' Python script in the 'misc' directory.

template<typename F>
inline void FemMatrix_Insert(SparseMatrixC<complex_t> &matrix, size_t row, size_t col, F value) {
	if(row != INDEX_NONE && col != INDEX_NONE) {
		matrix.Insert(row, col, value);
	}
}

void FemMatrix_EMPot_Rect(SparseMatrixC<complex_t> matrix[3], size_t vars[12], real_t delta_x, real_t delta_y, real_t omega,
		complex_t permittivity_x, complex_t permittivity_y, complex_t permittivity_z,
		complex_t permeability_x, complex_t permeability_y, complex_t permeability_z) {
	FemMatrix_Insert(matrix[0], vars[0], vars[0], -1.0/3.0*delta_x*permittivity_y/delta_y - 1.0/3.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[0], vars[1], -1.0/6.0*delta_x*permittivity_y/delta_y + (1.0/3.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[0], vars[2], (1.0/3.0)*delta_x*permittivity_y/delta_y - 1.0/6.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[0], vars[3], (1.0/6.0)*delta_x*permittivity_y/delta_y + (1.0/6.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[0], vars[4], (1.0/3.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[0], vars[5], (1.0/6.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[0], vars[6], (1.0/3.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[0], vars[7], (1.0/6.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[1], vars[0], -1.0/6.0*delta_x*permittivity_y/delta_y + (1.0/3.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[1], vars[1], -1.0/3.0*delta_x*permittivity_y/delta_y - 1.0/3.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[1], vars[2], (1.0/6.0)*delta_x*permittivity_y/delta_y + (1.0/6.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[1], vars[3], (1.0/3.0)*delta_x*permittivity_y/delta_y - 1.0/6.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[1], vars[4], -1.0/3.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[1], vars[5], -1.0/6.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[1], vars[6], (1.0/6.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[1], vars[7], (1.0/3.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[2], vars[0], (1.0/3.0)*delta_x*permittivity_y/delta_y - 1.0/6.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[2], vars[1], (1.0/6.0)*delta_x*permittivity_y/delta_y + (1.0/6.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[2], vars[2], -1.0/3.0*delta_x*permittivity_y/delta_y - 1.0/3.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[2], vars[3], -1.0/6.0*delta_x*permittivity_y/delta_y + (1.0/3.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[2], vars[4], (1.0/6.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[2], vars[5], (1.0/3.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[2], vars[6], -1.0/3.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[2], vars[7], -1.0/6.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[3], vars[0], (1.0/6.0)*delta_x*permittivity_y/delta_y + (1.0/6.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[3], vars[1], (1.0/3.0)*delta_x*permittivity_y/delta_y - 1.0/6.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[3], vars[2], -1.0/6.0*delta_x*permittivity_y/delta_y + (1.0/3.0)*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[3], vars[3], -1.0/3.0*delta_x*permittivity_y/delta_y - 1.0/3.0*delta_y*permittivity_x/delta_x);
	FemMatrix_Insert(matrix[0], vars[3], vars[4], -1.0/6.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[3], vars[5], -1.0/3.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[3], vars[6], -1.0/6.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[3], vars[7], -1.0/3.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[4], vars[0], (1.0/3.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[4], vars[1], -1.0/3.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[4], vars[2], (1.0/6.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[4], vars[3], -1.0/6.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[4], vars[4], -1.0/3.0*delta_x*delta_y*square(omega)*permittivity_x + delta_x/(delta_y*permeability_z));
	FemMatrix_Insert(matrix[0], vars[4], vars[5], -1.0/6.0*delta_x*delta_y*square(omega)*permittivity_x - delta_x/(delta_y*permeability_z));
	FemMatrix_Insert(matrix[0], vars[4], vars[6], -1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[4], vars[7], 1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[5], vars[0], (1.0/6.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[5], vars[1], -1.0/6.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[5], vars[2], (1.0/3.0)*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[5], vars[3], -1.0/3.0*delta_y*omega*permittivity_x);
	FemMatrix_Insert(matrix[0], vars[5], vars[4], -1.0/6.0*delta_x*delta_y*square(omega)*permittivity_x - delta_x/(delta_y*permeability_z));
	FemMatrix_Insert(matrix[0], vars[5], vars[5], -1.0/3.0*delta_x*delta_y*square(omega)*permittivity_x + delta_x/(delta_y*permeability_z));
	FemMatrix_Insert(matrix[0], vars[5], vars[6], 1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[5], vars[7], -1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[6], vars[0], (1.0/3.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[6], vars[1], (1.0/6.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[6], vars[2], -1.0/3.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[6], vars[3], -1.0/6.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[6], vars[4], -1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[6], vars[5], 1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[6], vars[6], -1.0/3.0*delta_x*delta_y*square(omega)*permittivity_y + delta_y/(delta_x*permeability_z));
	FemMatrix_Insert(matrix[0], vars[6], vars[7], -1.0/6.0*delta_x*delta_y*square(omega)*permittivity_y - delta_y/(delta_x*permeability_z));
	FemMatrix_Insert(matrix[0], vars[7], vars[0], (1.0/6.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[7], vars[1], (1.0/3.0)*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[7], vars[2], -1.0/6.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[7], vars[3], -1.0/3.0*delta_x*omega*permittivity_y);
	FemMatrix_Insert(matrix[0], vars[7], vars[4], 1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[7], vars[5], -1.0/permeability_z);
	FemMatrix_Insert(matrix[0], vars[7], vars[6], -1.0/6.0*delta_x*delta_y*square(omega)*permittivity_y - delta_y/(delta_x*permeability_z));
	FemMatrix_Insert(matrix[0], vars[7], vars[7], -1.0/3.0*delta_x*delta_y*square(omega)*permittivity_y + delta_y/(delta_x*permeability_z));
	FemMatrix_Insert(matrix[2], vars[0], vars[0], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[0], vars[1], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[0], vars[2], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[0], vars[3], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[0], vars[8], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[0], vars[9], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[0], vars[10], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[0], vars[11], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[0], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[1], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[2], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[3], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[8], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[9], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[10], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[1], vars[11], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[0], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[1], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[2], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[3], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[8], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[9], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[10], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[2], vars[11], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[0], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[1], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[2], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[3], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[8], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[9], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[10], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[3], vars[11], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[4], vars[4], -1.0/3.0*delta_x*delta_y/permeability_y);
	FemMatrix_Insert(matrix[2], vars[4], vars[5], -1.0/6.0*delta_x*delta_y/permeability_y);
	FemMatrix_Insert(matrix[2], vars[4], vars[8], -1.0/3.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[4], vars[9], (1.0/3.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[4], vars[10], -1.0/6.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[4], vars[11], (1.0/6.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[5], vars[4], -1.0/6.0*delta_x*delta_y/permeability_y);
	FemMatrix_Insert(matrix[2], vars[5], vars[5], -1.0/3.0*delta_x*delta_y/permeability_y);
	FemMatrix_Insert(matrix[2], vars[5], vars[8], -1.0/6.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[5], vars[9], (1.0/6.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[5], vars[10], -1.0/3.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[5], vars[11], (1.0/3.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[6], vars[6], -1.0/3.0*delta_x*delta_y/permeability_x);
	FemMatrix_Insert(matrix[2], vars[6], vars[7], -1.0/6.0*delta_x*delta_y/permeability_x);
	FemMatrix_Insert(matrix[2], vars[6], vars[8], -1.0/3.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[6], vars[9], -1.0/6.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[6], vars[10], (1.0/3.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[6], vars[11], (1.0/6.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[7], vars[6], -1.0/6.0*delta_x*delta_y/permeability_x);
	FemMatrix_Insert(matrix[2], vars[7], vars[7], -1.0/3.0*delta_x*delta_y/permeability_x);
	FemMatrix_Insert(matrix[2], vars[7], vars[8], -1.0/6.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[7], vars[9], -1.0/3.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[7], vars[10], (1.0/6.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[7], vars[11], (1.0/3.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[8], vars[0], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[8], vars[1], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[8], vars[2], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[8], vars[3], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[8], vars[4], -1.0/3.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[8], vars[5], -1.0/6.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[8], vars[6], -1.0/3.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[8], vars[7], -1.0/6.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[8], vars[8], (1.0/9.0)*delta_x*delta_y*permittivity_z - 1.0/3.0*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/3.0*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[8], vars[9], (1.0/18.0)*delta_x*delta_y*permittivity_z - 1.0/6.0*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/3.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[8], vars[10], (1.0/18.0)*delta_x*delta_y*permittivity_z + (1.0/3.0)*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/6.0*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[8], vars[11], (1.0/36.0)*delta_x*delta_y*permittivity_z + (1.0/6.0)*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/6.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[9], vars[0], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[9], vars[1], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[9], vars[2], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[9], vars[3], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[9], vars[4], (1.0/3.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[9], vars[5], (1.0/6.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[9], vars[6], -1.0/6.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[9], vars[7], -1.0/3.0*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[9], vars[8], (1.0/18.0)*delta_x*delta_y*permittivity_z - 1.0/6.0*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/3.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[9], vars[9], (1.0/9.0)*delta_x*delta_y*permittivity_z - 1.0/3.0*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/3.0*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[9], vars[10], (1.0/36.0)*delta_x*delta_y*permittivity_z + (1.0/6.0)*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/6.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[9], vars[11], (1.0/18.0)*delta_x*delta_y*permittivity_z + (1.0/3.0)*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/6.0*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[10], vars[0], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[10], vars[1], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[10], vars[2], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[10], vars[3], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[10], vars[4], -1.0/6.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[10], vars[5], -1.0/3.0*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[10], vars[6], (1.0/3.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[10], vars[7], (1.0/6.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[10], vars[8], (1.0/18.0)*delta_x*delta_y*permittivity_z + (1.0/3.0)*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/6.0*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[10], vars[9], (1.0/36.0)*delta_x*delta_y*permittivity_z + (1.0/6.0)*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/6.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[10], vars[10], (1.0/9.0)*delta_x*delta_y*permittivity_z - 1.0/3.0*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/3.0*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[10], vars[11], (1.0/18.0)*delta_x*delta_y*permittivity_z - 1.0/6.0*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/3.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[11], vars[0], (1.0/36.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[11], vars[1], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[11], vars[2], (1.0/18.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[11], vars[3], (1.0/9.0)*delta_x*delta_y*permittivity_z);
	FemMatrix_Insert(matrix[2], vars[11], vars[4], (1.0/6.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[11], vars[5], (1.0/3.0)*delta_y/(omega*permeability_y));
	FemMatrix_Insert(matrix[2], vars[11], vars[6], (1.0/6.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[11], vars[7], (1.0/3.0)*delta_x/(omega*permeability_x));
	FemMatrix_Insert(matrix[2], vars[11], vars[8], (1.0/36.0)*delta_x*delta_y*permittivity_z + (1.0/6.0)*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/6.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[11], vars[9], (1.0/18.0)*delta_x*delta_y*permittivity_z + (1.0/3.0)*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/6.0*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[11], vars[10], (1.0/18.0)*delta_x*delta_y*permittivity_z - 1.0/6.0*delta_x/(delta_y*square(omega)*permeability_x) + (1.0/3.0)*delta_y/(delta_x*square(omega)*permeability_y));
	FemMatrix_Insert(matrix[2], vars[11], vars[11], (1.0/9.0)*delta_x*delta_y*permittivity_z - 1.0/3.0*delta_x/(delta_y*square(omega)*permeability_x) - 1.0/3.0*delta_y/(delta_x*square(omega)*permeability_y));
}

void FemMatrix_EMPot_XLine(SparseMatrixC<complex_t> matrix[3], size_t vars[5], real_t delta_x, real_t omega, complex_t impedance) {
	constexpr complex_t I(0.0, 1.0);
	FemMatrix_Insert(matrix[0], vars[0], vars[0], I/(delta_x*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[0], vars[1], -I/(delta_x*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[0], vars[2], -I/impedance);
	FemMatrix_Insert(matrix[0], vars[1], vars[0], -I/(delta_x*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[1], vars[1], I/(delta_x*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[1], vars[2], I/impedance);
	FemMatrix_Insert(matrix[0], vars[2], vars[0], -I/impedance);
	FemMatrix_Insert(matrix[0], vars[2], vars[1], I/impedance);
	FemMatrix_Insert(matrix[0], vars[2], vars[2], I*delta_x*omega/impedance);
	FemMatrix_Insert(matrix[2], vars[0], vars[0], -1.0/3.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[0], vars[1], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[0], vars[3], -1.0/3.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[0], vars[4], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[0], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[1], -1.0/3.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[3], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[4], -1.0/3.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[0], -1.0/3.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[1], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[3], -1.0/3.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[4], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[0], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[1], -1.0/3.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[3], -1.0/6.0*I*delta_x/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[4], -1.0/3.0*I*delta_x/(impedance*omega));
}

void FemMatrix_EMPot_YLine(SparseMatrixC<complex_t> matrix[3], size_t vars[5], real_t delta_y, real_t omega, complex_t impedance) {
	constexpr complex_t I(0.0, 1.0);
	FemMatrix_Insert(matrix[0], vars[0], vars[0], I/(delta_y*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[0], vars[1], -I/(delta_y*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[0], vars[2], -I/impedance);
	FemMatrix_Insert(matrix[0], vars[1], vars[0], -I/(delta_y*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[1], vars[1], I/(delta_y*impedance*omega));
	FemMatrix_Insert(matrix[0], vars[1], vars[2], I/impedance);
	FemMatrix_Insert(matrix[0], vars[2], vars[0], -I/impedance);
	FemMatrix_Insert(matrix[0], vars[2], vars[1], I/impedance);
	FemMatrix_Insert(matrix[0], vars[2], vars[2], I*delta_y*omega/impedance);
	FemMatrix_Insert(matrix[2], vars[0], vars[0], -1.0/3.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[0], vars[1], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[0], vars[3], -1.0/3.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[0], vars[4], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[0], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[1], -1.0/3.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[3], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[1], vars[4], -1.0/3.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[0], -1.0/3.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[1], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[3], -1.0/3.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[3], vars[4], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[0], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[1], -1.0/3.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[3], -1.0/6.0*I*delta_y/(impedance*omega));
	FemMatrix_Insert(matrix[2], vars[4], vars[4], -1.0/3.0*I*delta_y/(impedance*omega));
}
